

server:
  port: 8002
  context-path: /

spring:
  application:
    name: sso-site2
  #配置jsp视图     
  mvc:
    view:
      prefix: /WEB-INF/pages
      #suffix: .jsp
  #redis 配置     
  redis:
    host: 192.168.100.220
    port: 6379
    password: 123456
    ssl: false
    database: 0
    timeout: 6000
    pool:
      max-active: 8 #缺省值8
      max-idle: 8 #缺省值8
      min-idle: 0 #缺省值0
      max-wait: 3000 #缺省值-1
      
sso: 
  ssoServer:
    #sso-server 登录验证地址
    checkLoginUrl: http://www.mysso.com:9001/ssoUser_checkLogin
    #sso-server 退出地址
    logoutUrl:  http://www.mysso.com:9001/ssoUser_logout
  ssoClient:
    #客户端退出回调页面
    logoutPage: /logout
    
    