

server:
  port: 8001
  context-path: /
  session:
    cookie:
      http-only: true
  
 

spring:
  application:
    name: sso-site1
  #配置jsp视图     
  mvc:
    view:
      prefix: /WEB-INF/pages
      #suffix: .jsp
  #redis 配置     
  redis:
    host: 192.168.100.220
    port: 6379
    password: 123456
    ssl: false
    database: 0
    timeout: 6000
    pool:
      max-active: 8 #缺省值8
      max-idle: 8 #缺省值8
      min-idle: 0 #缺省值0
      max-wait: 3000 #缺省值-1

sso: 
  ssoServer:
    #sso验证用户是否登录 url
    checkLoginUrl: http://www.mysso.com:9001/ssoUser_checkLogin
    #sso用户退出 url 
    logoutUrl:  http://www.mysso.com:9001/ssoUser_logout
  ssoClient:
    #sso 客户端本地退出回调地址(浏览器重定向)
    logoutPage: /logout
    #sso 客户端拦截器过滤排除的路径，支持ant表达式
    excludePaths: /goods_*

    
    